general:
  gpu_index: 0
  seed: 42
  images_folder_test_DGX: ILSVRC2012_test_sampled
  images_folder_test_ES_DGX: ILSVRC2012_test_earlystopping
  images_folder_name_DGX: ILSVRC2012_val_Updated_DGX
  images_folder_name: ILSVRC2012_val - Updated
  images_gt_filename: ILSVRC2012_validation_ground_truth.txt
  wandb_project: run_seg_cls_4 #run_seg_cls_l1_vs_bce
  wandb_entity: yuvalasher #amit_eshel
vit:
  train_images_path: train_data #train_data_exp
  val_images_path: val_data #val_data_exp
  gpus: 1
  run_base_model: True
  activation_function: sigmoid # choose from here: [sigmoid, relu, softmax, None]
  segmentation_transformer_n_first_layers_to_freeze: 0
  add_epsilon_to_patches_scores: False
  is_sampled_train_data_uniformly: True
  is_sampled_val_data_uniformly: True
  normalize_by_max_patch: False
  is_mlp_on_segmentation: True
  is_clamp_between_0_to_1: True # otherwise it's mix-max-norm
  train_model_by_target_gt_class: True # TODO - Pay Attention - Important!
  model_name: google/vit-base-patch16-224
#  model_name: google/vit-base-patch16-384
#  model_name: facebook/deit-base-patch16-224
#  model_name: google/vit-large-patch16-224
#  model_name: WinKawaks/vit-small-patch16-224
  is_wolf_transforms: False
  img_size: 224 #384
  patch_size: 16
  n_heads: 12
  gumble_objectives:
    - objective_gumble_softmax
    - objective_gumble_minimize_softmax
    - objective_opposite_gumble_softmax
  freezing_classification_transformer: True
  freeze_classification_head: False
  num_labels: 1000
  save_every: 5
  images:
    - image_name: 00000118.JPEG # Black & White
      correct_class: 3
      contrastive_class:
  batch_size: 32
  default_root_dir: /raid/yuvalas/checkpoints #/home/yuvalas/explainability/research/checkpoints/token_classification
  plot_path: /home/yuvalas/explainability/research/plots/token_classification/
  enable_checkpointing: False
  start_epoch_to_evaluate: 1
  n_batches_to_visualize: 2
  n_epochs: 20
  n_epochs_to_optimize_stage_b: 25
  lr: 2.0e-3
  num_steps: 180
  print_every: 1
  discard_ratio: 0.6
  log: False
  verbose: False
  plot_visualizations: False
  temperature: 1
  objective: temp_softmax # bias_temp_softmax #temp_softmax #bias_temp_softmax #temp_softmax # objective_gumble_softmax #objective_gumble_minimize_softmax # objective_gumble_softmax # objective_gumble_minimize_softmax # objective_opposite_gumble_softmax, objective_gumble_softmax
  seg_cls:
    train_n_label_sample: 6
    val_n_label_sample: 1
    loss:
      normalize: False
      mask_loss: bce #choose l1, bce, entropy_softmax
      prediction_loss_mul: 1
      mask_loss_mul: 50
      is_ce_neg: False
      use_logits_only: False
    earlystopping:
      min_delta: 0.0001
      patience: 3
  loss: # not relevant
    kl_loss_multiplier: 0
    pred_loss_multiplier: 10
    entropy_loss_multiplier: 100
    l1_loss_multiplier: 0
    other_loss_multiplier: 0
  evaluation:
    original_image_name: 224x224.JPEG
    batch_size: 1
    experiment_folder_name: seg_cls
#    perturbation_type: pos