general:
  gpu_index: 0
  seed: 42
  images_folder_test_DGX: ILSVRC2012_test_sampled
  images_folder_test_ES_DGX: ILSVRC2012_test_earlystopping
  images_folder_name_DGX: ILSVRC2012_val_Updated_DGX
  images_folder_name: ILSVRC2012_val - Updated
  images_gt_filename: ILSVRC2012_validation_ground_truth.txt
  wandb_project: run_seg_cls_4 #run_seg_cls_l1_vs_bce
  wandb_entity: yuvalasher #amit_eshel
vit:
  train_images_path: train_data #train_data_exp
  val_images_path: val_data #val_data_exp
  gpus: 1
  run_base_model: True
  activation_function: sigmoid # choose from here: [sigmoid, relu, softmax, None]
  is_sampled_data_uniformly: True
  normalize_by_max_patch: False
  is_mlp_on_segmentation: True
  is_clamp_between_0_to_1: True # otherwise it's mix-max-norm
  model_name: google/vit-base-patch16-224
  img_size: 224
  patch_size: 16
  n_heads: 12
  gumble_objectives:
    - objective_gumble_softmax
    - objective_gumble_minimize_softmax
    - objective_opposite_gumble_softmax
  freezing_transformer: True
  freeze_classification_head: False
  num_labels: 1000
  save_every: 5
  images:
    #    - image_name: 1111111111 (1).JPEG
    #      correct_class: 3
    #      contrastive_class:
    #    - image_name: 00000069.JPEG # tricycle, trike, velocipede
    #      correct_class: 870
    #      contrastive_class:
    - image_name: 00000118.JPEG # Black & White
      correct_class: 3
      contrastive_class:
  #    - image_name: 0000000005.JPEG # catdog
  #      correct_class: 282 # cat
  #      contrastive_class: 243 # dog
  batch_size: 32
  default_root_dir: /home/amiteshel1/Projects/explainablity-transformer-cv/research/checkpoints/token_classification #/home/yuvalas/explainability/research/checkpoints/token_classification
  plot_path: /home/amiteshel1/Projects/explainablity-transformer-cv/research/plots
  enable_checkpointing: True
  start_epoch_to_evaluate: 1
  n_batches_to_visualize: 2
  n_epochs: 30
  lr: 2.0e-3
  num_steps: 180
  print_every: 1
  discard_ratio: 0.6
  log: False
  verbose: False
  plot_visualizations: False
  temperature: 1
  objective: temp_softmax # bias_temp_softmax #temp_softmax #bias_temp_softmax #temp_softmax # objective_gumble_softmax #objective_gumble_minimize_softmax # objective_gumble_softmax # objective_gumble_minimize_softmax # objective_opposite_gumble_softmax, objective_gumble_softmax
  is_wolf_transforms: False
  seg_cls:
    train_n_label_sample: 18
    val_n_label_sample: 1
    loss:
      normalize: False
      mask_loss: bce #choose l1, bce, entropy_softmax
      prediction_loss_mul: 1
      mask_loss_mul: 50
      is_ce_neg: False
      use_logits_only: True
    earlystopping:
      min_delta: 0.0001
      patience: 3
  loss: # not relevant
    kl_loss_multiplier: 0
    pred_loss_multiplier: 10
    entropy_loss_multiplier: 100
    l1_loss_multiplier: 0
    other_loss_multiplier: 0
  evaluation:
    original_image_name: 224x224.JPEG
    batch_size: 1
    experiment_folder_name: seg_cls
#    perturbation_type: pos
