general:
  seed: 42
  images_folder_name: ILSVRC2012_val
  images_gt_filename: ILSVRC2012_validation_ground_truth.txt

vit:
  dino_plots_folder_name: dino method on supervised vit - cls of the last layer to other tokens
  num_labels: 1000
  model_name: google/vit-base-patch16-384
  img_size: 384
  patch_size: 16
  stop_prob_criterion: 0.3
  sample_picture_name: ILSVRC2012_val_00000018.JPEG
  sample_images:
#    - ILSVRC2012_val_00000001.JPEG # sanke
#    - ILSVRC2012_val_00000003.JPEG # dog
#    - ILSVRC2012_val_00000009.JPEG # mousetrap
    - ILSVRC2012_val_00000018.JPEG # bird
  lr: 3.0e-01
  num_steps: 1000
  print_every: 1
  log: False
  verbose: True
  loss:
    pred_loss_multiplier: 1
    entropy_loss_multiplier: 1
    l1_loss_multiplier: 1