general:
  seed: 42
  images_folder_name: ILSVRC2012_val
  images_gt_filename: ILSVRC2012_validation_ground_truth.txt

vit:
  model_name: google/vit-base-patch16-384
  img_size: 384
  batch_size: 16
  lr: 2.0e-05
  gamma: 0.7
  n_epochs: 10
  n_classes: 6