general:
  seed: 42
  images_folder_name: ILSVRC2012_val
  images_gt_filename: ILSVRC2012_validation_ground_truth.txt

vit:
  small_number_for_stability: 1.0e-06
  lr: 3.0e-01
  model_name: google/vit-base-patch16-384
  img_size: 384
  stop_prob_criterion: 0.3
  sample_picture_name: ILSVRC2012_val_00000001.JPEG
  num_labels: 1000
  num_steps: 5
  print_every:
  log: False
  verbose: True
  loss:
    prediction_loss_multiplier: 10
